services:
  mysqldb:
    image: mysql:latest
    restart: always
    ports:
      - '3306:3306'
    volumes:
      - ./data:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=db
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass
#  postgresdb:
#    image: postgres:latest
#    ports:
#      - '5432:5432'
#    environment:
#      - POSTGRES_DB=app
#      - POSTGRES_USER=app
#      - POSTGRES_PASSWORD=pass